name: CI

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Super Validation Step
      run: echo How fascinating!
    
    - name: The Final Validation
      run: echo Now learn further
